title: Default
sections:
  main:
    display: Main
    fields:
      title:
        type: text
        width: 33
        localizable: true
        display: Title
        instructions: 'Longer page title'
      slug:
        type: text
        width: 33
        instructions: 'The unique part of the url, shorter is better'
      nav_title:
        type: text
        instructions: 'The shorter title displayed in the navigation'
        width: 33
        display: 'Navigation Title'
      page_content:
        sets:
          one_column_block:
            display: 'One Column Block'
            fields:
              block_content:
                settings: Standard
                restrict_assets: false
                type: redactor
                display: Content
                container: main
                width: 50
              class:
                options:
                  centered: Centered
                  intro: 'Large Intro Text'
                  reverse: 'White on Red'
                  full-width: 'Full Width'
                type: checkboxes
                display: 'Layout Features'
          two_column_block:
            display: 'Two Column Block'
            fields:
              column_1:
                restrict_assets: false
                type: redactor
                width: 50
                display: 'Column 1'
                container: main
                folder: /
              column_2:
                restrict_assets: false
                type: redactor
                width: 50
                display: 'Column 2'
                container: main
                folder: /
          three_column_block:
            display: 'Three Column Block'
            fields:
              column_1:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 1'
                container: main
                folder: /
              column_2:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 2'
                container: main
                folder: /
              column_3:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 3'
                container: main
                folder: /
          four_column_block:
            display: 'Four Column Block'
            fields:
              column_1:
                restrict_assets: false
                type: redactor
                width: 25
                display: 'Column 1'
                container: main
                folder: /
              column_2:
                restrict_assets: false
                type: redactor
                width: 25
                display: 'Column 2'
                container: main
                folder: /
              column_3:
                restrict_assets: false
                type: redactor
                width: 25
                display: 'Column 3'
                container: main
                folder: /
              column_4:
                restrict_assets: false
                type: redactor
                width: 25
                display: 'Column 4'
                container: main
                folder: /
          five_column_block:
            display: 'Five Column Block'
            fields:
              heading:
                type: text
                display: Heading
              column_1:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 1'
                container: main
                folder: /
              column_2:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 2'
                container: main
                folder: /
              column_3:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 3'
                container: main
              column_4:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 4'
                container: main
                folder: /
              column_5:
                restrict_assets: false
                type: redactor
                width: 33
                display: 'Column 5'
                container: main
                folder: /
              class:
                options:
                  centered: 'Centered Heading'
                  reverse: 'White on Red'
                type: checkboxes
                display: 'Layout Features'
          simple_text_block:
            display: 'Simple Text Block'
            fields:
              text_block:
                container: main
                folder: /
                restrict_assets: false
                type: redactor
                display: 'Text Block'
          form_block:
            display: 'Form Block'
            fields:
              form:
                type: form
                display: Form
                width: 50
          asset_gallery:
            display: 'Asset Gallery'
            fields:
              gallery_heading:
                type: text
                display: 'Gallery Heading'
              assets_selection:
                container: main
                folder: On-the-ground
                restrict: false
                type: assets
                display: 'Selected Assets'
                mode: grid
        type: replicator
        display: 'Page Content'
  page_settings:
    display: 'Page Settings'
    fields:
      hide_from_top_nav:
        type: toggle
        width: 33
        display: 'Hide from top nav'
      class:
        type: text
        instructions: 'Specify a class name for this page''s entry in the nav'
        width: 33
        display: Class
      template:
        type: template
        width: 33
        display: Template
taxonomies: true
